### ISSUE TITLE
Problem on displaying reviews in loop

### ISSUE THREAD

**Issue by MarkGersaliaPH** [dgvai/laravel-user-review#1]
Hello Guys, I can't display the review on loop

`	@php
$rate = $product->reviews();
															foreach($rate as $rating){
																echo $rating->review_text;
															}
														@endphp`

But when im using 

`$reviews = $product->reviews();
        $review = $reviews->first();
        dd($review->review_text);`

It displays the first item of reviews.

Can someone help me? 

sorry for my english.

**Comment by dgvai** [comment]
@MarkGersaliaPH your product may contain one "active" review, you may check your database. 
Second suggestions, you may also try `$product->reviews` instead

**Comment by MarkGersaliaPH** [comment]
Thank you.. its now working `$product->reviews` is the key
