### ISSUE TITLE
Support for PHP 8 or Laravel 9

### ISSUE THREAD

**Issue by jerexbambex** [dgvai/laravel-user-review#9]
I am having this error because of my PHP version
```
Problem 1
    - dgvai/laravel-user-review[1.4, ..., 1.5.1] require php ^7.2 -> your php version (8.1.10) does not satisfy that requirement.
    - Root composer.json requires dgvai/laravel-user-review ^1.4 -> satisfiable by dgvai/laravel-user-review[1.4, 1.5, 1.5.1].
```

Please any plan for PHP >=8 support?

**Comment by backlink-market** [comment]
same here, please fix

**Comment by dgvai** [comment]
https://github.com/dgvai/laravel-user-review/releases/tag/v2

**Comment by backlink-market** [comment]
why not make it downwards compatible with "^7.4|^8.0" ?

**Comment by jerexbambex** [comment]
This is exactly what I did in my composer.json file.

**Comment by backlink-market** [comment]
> This is exactly what I did in my composer.json file.

yep, it was ment to target @dgvai because it was updated to just use the 8.0
